"""
Named launchers — clean Login Items names for every AOS LaunchAgent.

macOS Background Task Management (System Settings → General → Login Items &
Extensions) displays a launchd item by its *executable's* filename, not its
label. A plist whose ProgramArguments starts with /bin/bash or a venv python
shows up as "bash" or "python" — an unreadable wall when a machine runs
twenty services.

The fix is a canonical transform: every service plist points at a small
exec-wrapper script in ~/.aos/launchers/ whose FILENAME is the display name
("AOS Bridge"). The wrapper `exec`s the real command, so launchd still tracks
the true process (KeepAlive semantics unchanged) and BTM shows the clean name.

This module is the single source of that transform. Everything that touches
service plists — migrations, installers, reconcile checks — goes through it
so the plist on disk, the launcher content, and the drift checks can never
disagree about what "correct" looks like.

Layers (component lifecycle):
  framework  — this module, templates keep their REAL command lines
  instance   — ~/.aos/launchers/* generated per machine at deploy/reconcile
  runtime    — launchd executes the launcher; BTM displays its filename
"""

from __future__ import annotations

import plistlib
import re
import shlex
from pathlib import Path

HOME = Path.home()
LAUNCHERS_DIR = HOME / ".aos" / "launchers"

# Executables that make Login Items unreadable when used as arg0.
INTERPRETERS = {
    "bash", "sh", "zsh", "dash",
    "python", "python3", "node", "bun", "deno", "ruby", "perl",
    "uvicorn", "gunicorn",
}
# Also match versioned interpreters: python3.13, node22, ...
_VERSIONED = re.compile(r"^(python|node|ruby|perl)[\d.]*$")

_HEADER = (
    "#!/bin/bash\n"
    "# AOS launcher for {label} — the filename is the Login Items display name.\n"
    "# Generated by core/infra/lib/launchers.py. Do not edit or rename;\n"
    "# regenerate via reconcile (launcher_naming) or the service installer.\n"
)


def is_ugly_arg0(arg0: str) -> bool:
    """True when arg0's basename would render as an interpreter name in BTM."""
    base = Path(arg0).name
    return base in INTERPRETERS or bool(_VERSIONED.match(base))


# Casing that plain .capitalize() gets wrong.
_SPECIAL_WORDS = {
    "ios": "iOS", "macos": "macOS", "whatsmeow": "WhatsApp",
    "api": "API", "mcp": "MCP", "ai": "AI",
}


def derive_display_name(label: str) -> str:
    """Fallback display name from a launchd label.

    com.aos.work-runner -> "AOS Work Runner"
    com.aos.ios-deploy  -> "AOS iOS Deploy"
    am.hish.adhan.audio -> "Adhan Audio"
    """
    parts = label.split(".")
    # Drop reverse-DNS prefix (com/org/am + vendor) when present.
    tail = parts[2:] if len(parts) > 2 else parts[-1:]
    words: list[str] = []
    if len(parts) > 1 and parts[1] == "aos":
        words.append("AOS")
    for part in tail:
        for w in re.split(r"[-_]", part):
            if not w:
                continue
            special = _SPECIAL_WORDS.get(w.lower())
            words.append(special or (w if w.isupper() else w.capitalize()))
    return " ".join(words) or label


def launcher_path(display_name: str) -> Path:
    return LAUNCHERS_DIR / display_name


def build_launcher_text(label: str, args: list[str]) -> str:
    cmd = " ".join(shlex.quote(a) for a in args)
    return _HEADER.format(label=label) + f'exec {cmd} "$@"\n'


def read_plist(plist_path: Path) -> dict:
    with open(plist_path, "rb") as f:
        return plistlib.load(f)


def effective_args(pl: dict) -> list[str] | None:
    """The command a plist runs, whether via Program or ProgramArguments."""
    args = pl.get("ProgramArguments")
    if args:
        return list(args)
    if "Program" in pl:
        return [pl["Program"]]
    return None


def is_wrapped(pl: dict) -> bool:
    """True when the plist already points at a generated launcher."""
    args = effective_args(pl)
    return bool(args) and len(args) == 1 and args[0].startswith(str(LAUNCHERS_DIR) + "/")


def canonical_plist_bytes(rendered: bytes | str, display_name: str) -> bytes:
    """What a deployed plist SHOULD look like after the launcher transform.

    Takes a rendered template (real command line) and returns the plist with
    ProgramArguments replaced by the launcher path. Drift checks compare the
    deployed plist against this, so templates keep the real command as the
    single source of truth.
    """
    if isinstance(rendered, str):
        rendered = rendered.encode()
    pl = plistlib.loads(rendered)
    pl.pop("Program", None)
    pl["ProgramArguments"] = [str(launcher_path(display_name))]
    return plistlib.dumps(pl)


def expected_launcher_text(rendered: bytes | str, label: str) -> str:
    """The launcher content implied by a rendered template."""
    if isinstance(rendered, str):
        rendered = rendered.encode()
    args = effective_args(plistlib.loads(rendered))
    if not args:
        raise ValueError(f"{label}: template has no Program/ProgramArguments")
    return build_launcher_text(label, args)


def ensure_launcher(label: str, plist_path: Path, display_name: str | None = None) -> tuple[bool, str]:
    """Idempotently apply the launcher transform to a deployed plist.

    Returns (changed, display_name). Writes the launcher from the plist's
    CURRENT command line, then rewrites the plist to point at it. Safe to
    re-run: an already-wrapped plist only has its launcher refreshed if the
    file went missing.
    """
    name = display_name or derive_display_name(label)
    pl = read_plist(plist_path)
    args = effective_args(pl)
    if not args:
        raise ValueError(f"{label}: no Program/ProgramArguments in {plist_path}")

    LAUNCHERS_DIR.mkdir(parents=True, exist_ok=True)
    lp = launcher_path(name)

    if is_wrapped(pl):
        # Plist already points at a launcher; make sure the file exists.
        wrapped_target = Path(args[0])
        if wrapped_target.exists():
            return False, name
        raise ValueError(
            f"{label}: plist points at missing launcher {wrapped_target} — "
            "cannot regenerate (real command unknown); redeploy the service"
        )

    lp.write_text(build_launcher_text(label, args))
    lp.chmod(0o755)
    pl.pop("Program", None)
    pl["ProgramArguments"] = [str(lp)]
    with open(plist_path, "wb") as f:
        plistlib.dump(pl, f)
    return True, name
