#!/usr/bin/env bash
# Full auto to TestFlight for a project generated by new-ios-app.
#   ship.sh <project_dir>
# Registers the bundle ID + creates the App Store Connect record (idempotent),
# builds, signs (automatic), and uploads a first TestFlight build.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"

PROJ="${1:?usage: ship.sh <project_dir>}"
PROJ="$(cd "$PROJ" && pwd)"
[ -f "$PROJ/.aos-app.env" ] || { echo "ERROR: $PROJ/.aos-app.env not found — is this a new-ios-app project?" >&2; exit 1; }

# Load Apple credentials (Keychain) + the per-app metadata.
# shellcheck disable=SC1091
source "$HERE/credentials.sh"
# shellcheck disable=SC1091
set -a; source "$PROJ/.aos-app.env"; set +a

echo "==> Shipping $APP_NAME ($APP_BUNDLE_ID) to TestFlight"
cd "$PROJ"
xcodegen generate
exec fastlane ios ship
